// This file will be auto-generated by the Supabase CLI
// after you run 'npx supabase gen types typescript --project-id <your-project-id> > src/types/database.types.ts'
// For now, it's a placeholder.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      // You will see your tables here, for example:
      // clients: { ... }
    }
    Views: {
      // You will see your views here
    }
    Functions: {
      // You will see your functions here
    }
    Enums: {
      // You will see your enums here
    }
    CompositeTypes: {
      // You will see your composite types here
    }
  }
}
